### ISSUE TITLE
Add phpMyAdmin

### ISSUE THREAD

**Issue by openp2pdesign** [openp2pdesign/OSVH_Platform#1]
https://hub.docker.com/r/phpmyadmin/phpmyadmin/

**Comment by openp2pdesign** [comment]
```
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
```
